### ISSUE TITLE
Load Mesh files, Export histogram computation as .csv ad plot

### ISSUE THREAD

**Issue by sivaranjanija** [prascle/CloudComPy#1]
Hello!
Thanks for developing this CloudComPy API for CloudCompare. I am using CloudComPy to try the following:

* Open/load ".fbx" mesh filetype - I couldn't figure out the API to load a mesh (But, I see that the ccMesh class exists with many functionalities)
* Export the results of distance computation (i.e, Histogram of the cloud to cloud distance computation and export these results as .csv file and .png fig
![image](https://user-images.githubusercontent.com/66548230/126522171-558fb45f-e44e-4297-b0fd-dee5ce646e1f.png)
It would be great if you could let me know whether these functionalities are there in CloudComPy, or, intended to be developed sooner.
Thank you!

**Comment by prascle** [comment]
Hello,
I answered [here](https://github.com/CloudCompare/CloudComPy/issues/6) :-)

**Comment by sivaranjanija** [comment]
Thank you!
