### ISSUE TITLE
Cloud2Mesh distance bug

### ISSUE THREAD

**Issue by andreabonvini** [prascle/CloudComPy#2]
Hi,
What would be necessary to do in order to update the PythonAPI in light of this bug: https://github.com/CloudCompare/CloudCompare/issues/1672  ? I think the passage to CloudCompare v2.12.4 should be incuded in the current July's release. I would be happy to help if necessary, thanks.

**Comment by andreabonvini** [comment]
Ok, thanks for the good work!

**Comment by andreabonvini** [comment]
Hi, is there any update on when the new CloudComPy version will be available?

**Comment by prascle** [comment]
Hi,
I published a new version a week ago!
See [the CloudCompare GitHub](https://github.com/CloudCompare/CloudComPy/pull/63) and [the binaries](https://www.simulation.openfields.fr/index.php/download-binaries)

Paul
